name: test slurk

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 flake8

      - name: Lint with autopep8
        run: |
          autopep8 --exit-code . || (git --no-pager diff .; exit 1)

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics


  Test:
    runs-on: ubuntu-latest
    needs:
      - Lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest --runxfail --color=yes --missing-dependency-action=fail


  Documentation:
    runs-on: ubuntu-latest
    needs:
      - Test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinxcontrib-openapi sphinx_rtd_theme
          pip install -r requirements.txt

      - name: Generate documentation
        env:
          DATABASE: sqlite:///
          FLASK_APP: app
        run: |
          flask openapi write docs/openapi.json
          (cd docs && make html)
          cp docs/slurk_api_rapidoc.html docs/openapi.json docs/_build/html/
          touch docs/_build/html/.nojekyll

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ./docs/_build/html

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
